djangoToDoApp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("todo.urls", namespace='todo'))
]

todo/urls.py
from django.urls import path
from .import views

app_name = "todo"
urlpatterns = [
    path('', views.indexView, name="index"),
    path("create/", views.createTodo, name="create"),
    path("delete/<int:todo_id>", views.deleteTodo, name="delete"),
    path("done/<int:todo_id>", views.doneTodo, name="done"),
    path("deleteAll/", views.deleteAllDonedTodos , name="deleteAllDonedTodos"),
    path("update/<pk>",views.UpdateTodoView.as_view(), name='update'),
    path("result/",views.search, name='search'),
]

todo/models.py
from django.db import models
from django.shortcuts import redirect
# Create your models here.
class Todo(models.Model):
	PRIORITIES = (
		('bg-warning', 'RED'),
		('bg-success', 'GREEN'),
		('bg-danger', 'YELLOW'),
		)
	title = models.CharField('Title',max_length=200)
	text = models.CharField('Text', max_length=800,blank=True)
	date = models.DateTimeField('Time', auto_now_add=True)
	done = models.BooleanField('Done ?', default=False)
	priority = models.CharField('Priority',max_length=50,choices=PRIORITIES, blank=True)

	# def doned(self):
	# 	self.done = False
	# 	self.save()
	# 	return redirect("/")

	def __str__(self):
		return self.title

	class Meta:
		ordering = ['-id']

todo/forms.py
from django import forms
from .models import Todo

class TodoAddForm(forms.ModelForm):

	class Meta:
		model = Todo
		fields = '__all__'
		exclude = ('done',)

todo/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from .models import Todo
from .forms import TodoAddForm
from django.views.generic.edit import UpdateView
from django.db.models import Q
# Create your views here.
def indexView(request):
    todos = Todo.objects.filter(done=False)
    doned_todos = Todo.objects.filter(done=True)
    return render(request, "index.html", {"tasks":todos, "doned_todos":doned_todos})

def doneTodo(request, todo_id):
    todo = Todo.objects.get(id=todo_id)
    todo.done = True
    todo.save()
    if todo:
        return redirect("/")
    return render(request, 'index.html')

def createTodo(request):
    if request.method == "POST":
        form = TodoAddForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("todo:index")
    else:
        form = TodoAddForm()
    return render(request, "todo.html", {"form":form})

def deleteTodo(request, todo_id):
    todo = Todo.objects.get(id=todo_id)
    todo.delete()
    return redirect("/")


def deleteAllDonedTodos(request):
    doned_todos = Todo.objects.filter(done=True)
    doned_todos.delete()
    return redirect("/")


class UpdateTodoView(UpdateView):
    model = Todo
    fields = ['title', 'text', 'priority']
    template_name = 'todo.html'
    success_url = '/'

import json
def search(request):
    d = json.loads(request.GET["data"])
    print(d)
    obj = list(Todo.objects.filter(
    Q(title__icontains=d) | Q(text__icontains=d)).values())
    data = {}
    data["data"] = obj
    return JsonResponse(data)

templates/index.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" integrity="sha512-Fo3rlrZj/k7ujTnHg4CGR2D7kSs0v4LLanw2qksYuRlEzO+tcaEPQogQ0KaoGN26/zrn20ImR1DfuLWnOo7aBA==" crossorigin="anonymous" referrerpolicy="no-referrer"
    />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <title>ToDo App Django</title>
</head>

<body>
    <div class="container mt-5">
        <div class="row">
            <div class="col-sm-12 col-md-9">
                <h1>Todos</h1>
                <div class="card">
                    <div class="card-header bg-warning">
                        <div class="row">
                            <div class="col-sm-10">
                                <h3>Add a new Task</h3>
                            </div>
                            <div class="col-sm-2">
                                <a href="{% url 'todo:create' %}" class="h2 text-primary">
                                    <i class="fas fa-plus-circle"></i>
                                </a>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        {% for task in tasks %}
                        <div class="card mt-3 p-3 {{ task.priority }}">
                            <div class="row">
                                <div class="col-sm-9">
                                    <div class="card-title">
                                        <h4>{{ task.title }} </h4>
                                    </div>
                                    <div class="card-text">
                                        <p>{{ task.text }}</p>
                                        <p>
                                            <i class="fas fa-calendar"></i> {{ task.date|date:"d/m/Y" }}
                                            <i class="fas fa-clock"></i> {{ task.date|date:"h:m:s" }}</p>
                                    </div>
                                </div>
                                <div class="col-sm-3">
                                    <a href="{% url 'todo:done' task.id %}" class=" btn btn-info ">
                                        <i class="fas fa-check "></i>
                                    </a>
                                    <a href="{% url 'todo:update' task.id %} " class="btn btn-info ">
                                        <i class="fas fa-refresh "></i>
                                    </a>
                                    <a href="{% url 'todo:delete' task.id %} " class="btn btn-info ">
                                        <i class="fas fa-trash "></i>
                                    </a>
                                </div>
                            </div>

                        </div>
                        {% endfor %}


                    </div>
                </div>
            </div>
            <div class="col-sm-12 col-md-3 ">
                <h2>Done Todos</h2>
                <br>

                <div class="card ">
                    <div class="card-header">
                        <form action="" method="get" onkeyup="InlineSearch(this[0].value)">
                            <input type="text" placeholder="Search">
                        </form>
                    </div>
                    <div class="card-body ">
                        <span id="result_list">

                        </span>
                        <h4>Doned todos</h4>
                        {% for doned_todo in doned_todos %}
                        <div class="card p-2 mt-3 {{ doned_todo.priority }} ">
                            <div class="card-title ">
                                {{ doned_todo.title }}
                            </div>
                        </div>
                        {% endfor %}

                    </div>
                    <div class="card-footer ">
                        <a href="{% url 'todo:deleteAllDonedTodos' %} " class="btn btn-danger ">
                   Delete All  <i class="fas fa-trash "></i>
                </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script>
        function InlineSearch(query) {
            console.log(query)
            let data = JSON.stringify(query)
            if (window.XMLHttpRequest) {
                var xhttp = new XMLHttpRequest();
            } else { // code for IE6, IE5
                var xhttp = new ActiveXObject("Microsoft.XMLHTTP");
            }
            xhttp.onreadystatechange = function() {
                if (xhttp.readyState === 4 && xhttp.status === 200) {
                    var data = JSON.parse(this.responseText);
                    console.log(data)
                    let list = document.querySelector("#result_list")
                    let elem = `<span>`
                    for (let i = 0; i < data.data.length; i++) {

                        obj = data.data[i]
                        let panel = `<a class="panel-block" href="/post/${obj.slug}">
                        <span class="panel-icon">
                            <i class="${obj.icon}" aria-hidden="true"></i>
                          </span> ${obj.title}</a>
                        `
                        elem += panel
                    }
                    elem += `</span>`
                    console.log(elem)
                    list.innerHTML = elem



                } else {

                }
            }
            var url = "/result/"
            xhttp.open("GET", url + `?data=${data}`, true);
            xhttp.send();
        }
    </script>
</body>

</html>

templates/result.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" integrity="sha512-Fo3rlrZj/k7ujTnHg4CGR2D7kSs0v4LLanw2qksYuRlEzO+tcaEPQogQ0KaoGN26/zrn20ImR1DfuLWnOo7aBA==" crossorigin="anonymous" referrerpolicy="no-referrer"
    />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <title>Results App Django</title>
</head>

<body>
    <div class="container mt-5">
        <div class="row">
            <div class="col-sm-12 col-md-6">
                <h3>{{object.title}}</h3>
                <p>{{object.text}}</p>
            </div>
        </div>
    </div>
</body>

</html>

templates/todo.html
{% load crispy_forms_tags %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" integrity="sha512-Fo3rlrZj/k7ujTnHg4CGR2D7kSs0v4LLanw2qksYuRlEzO+tcaEPQogQ0KaoGN26/zrn20ImR1DfuLWnOo7aBA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <title>ToDo App Django</title>
</head>
<body>
<div class="container mt-5">
    <div class="row">
        <div class="col-sm-12 col-md-9">
            <h1>Todos <a href="/"> <i class="fas fa-home"></i></a></h1>
            <div class="card">
                <div class="card-header bg-warning">
                    <div class="row">
                        <div class="col-sm-12">
                            <h3>Add a new Task</h3>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <div class="card p-5">
                        <form action="" method="post">
                            {% csrf_token %}
                            {{ form|crispy }}
                            <input type="submit" class="btn btn-block bg-warning">
                        </form>
                    </div>
                </div>
                <div class="card-footer">

                </div>
            </div>
        </div>
        <div class="col-sm-12 col-md-3">
            <h2>Done Todos</h2>
        </div>
    </div>
</div>
</body>
</html>